workspace(name = "io_frobozzco_rules_bootcamp")

load(
    "@io_frobozzco_rules_bootcamp//bootcamp:bootcamp.bzl",
    "rules_bootcamp_deps",
    "rules_bootcamp_toolchains",
)

rules_bootcamp_deps()

load("@rules_java//java:repositories.bzl", "rules_java_dependencies", "rules_java_toolchains")

rules_java_dependencies()
rules_java_toolchains()

load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")

rules_proto_dependencies()
rules_proto_toolchains()

load("@io_frobozzco_rules_bootcamp//bootcamp:config.bzl", "bootcamp_config")

bootcamp_config(
    versions = ["1.2.3", "4.5.6", "7.8.9"],
)

rules_bootcamp_toolchains()

