workspace(name = "io_frobozzco_rules_bootcamp")

load("@io_frobozzco_rules_bootcamp//bootcamp:deps.bzl", "rules_bootcamp_deps")

rules_bootcamp_deps()

load("@rules_java//java:repositories.bzl", "rules_java_dependencies", "rules_java_toolchains")

rules_java_dependencies()
rules_java_toolchains()

load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")

rules_proto_dependencies()
rules_java_toolchains()
rules_proto_toolchains()

load("@io_frobozzco_rules_bootcamp//bootcamp:config.bzl", "bootcamp_config")

bootcamp_config()

load(
    "@io_frobozzco_rules_bootcamp//bootcamp:bootcamp.bzl",
    "bootcamp_register_toolchains",
)

bootcamp_register_toolchains()

