# Copyright 2025 EngFlow, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

workspace(name = "bzlmod_bootcamp")

local_repository(
    name = "com_frobozz_rules_magic",
    path = "../rules_magic",
)

load("@com_frobozz_rules_magic//magic:config.bzl", "magic_config")

magic_config(
    games = [
        "enchanter",
        "sorcerer",
        "spellbreaker",
    ],
    versions = [
        "1.2.3",
        "4.5.6",
        "7.8.9",
    ],
)

load(
    "@com_frobozz_rules_magic//magic:magic.bzl",
    "rules_magic_deps",
    "rules_magic_leaflet_repository",
    "rules_magic_toolchains",
)

rules_magic_deps()

load("@rules_python//python:repositories.bzl", "py_repositories")

py_repositories()

# Note that `rules_java` 8.x suggests loading `protobuf_deps()` after
# `rules_java_dependencies` and before `rules_java_toolchains()`:
# - https://github.com/bazelbuild/rules_java/releases/tag/8.9.0
#
# `rules_java` 7.x also works with this ordering.
load(
    "@rules_java//java:repositories.bzl",
    "rules_java_dependencies",
    "rules_java_toolchains",
)

rules_java_dependencies()

load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")

protobuf_deps()

rules_java_toolchains()

rules_magic_leaflet_repository()

rules_magic_toolchains()
