# Copyright 2025 EngFlow, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

workspace(name = "rules_magic")

load("//magic:config.bzl", "magic_config")

magic_config(
    versions = [
        "1.2.3",
        "4.5.6",
        "7.8.9",
    ],
)

load("//magic:magic.bzl", "rules_magic_deps", "rules_magic_toolchains")

rules_magic_deps()

# Required by rules_java >= 8.16.0:
# - https://github.com/bazelbuild/rules_java/releases/tag/8.16.0
load("@bazel_features//:deps.bzl", "bazel_features_deps")

bazel_features_deps()

# Required by rules_cc >= 0.2.0
# - https://github.com/bazelbuild/rules_cc/releases/tag/0.2.0
load("@rules_cc//cc:extensions.bzl", "compatibility_proxy_repo")

compatibility_proxy_repo()

# Note that `rules_java` 8.x suggests loading `protobuf_deps()` after
# `rules_java_dependencies` and before `rules_java_toolchains()`:
# - https://github.com/bazelbuild/rules_java/releases/tag/8.9.0
#
# `rules_java` 7.x also works with this ordering.
load("@rules_java//java:rules_java_deps.bzl", "rules_java_dependencies")

rules_java_dependencies()

load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")

protobuf_deps()

load("@rules_java//java:repositories.bzl", "rules_java_toolchains")

rules_java_toolchains()

# Comes after `protobuf_deps` so `protobuf` gets the version of `bazel_skylib`
# that it needs.
load("@rules_python//python:repositories.bzl", "py_repositories")

py_repositories()

rules_magic_toolchains()
