workspace(name = "com_frobozz_rules_magic")

load(
    "@com_frobozz_rules_magic//magic:magic.bzl",
    "rules_magic_deps",
    "rules_magic_toolchains",
)

rules_magic_deps()

load(
    "@rules_java//java:repositories.bzl",
    "rules_java_dependencies",
    "rules_java_toolchains",
)

rules_java_dependencies()
rules_java_toolchains()

load(
    "@rules_proto//proto:repositories.bzl",
    "rules_proto_dependencies",
    "rules_proto_toolchains",
)

rules_proto_dependencies()
rules_proto_toolchains()

load("@com_frobozz_rules_magic//magic:config.bzl", "magic_config")

magic_config(
    versions = ["1.2.3", "4.5.6", "7.8.9"],
)

rules_magic_toolchains()
